# SPARQL for Scotland IMD 
# Paste everything below into http://statistics.gov.scot/sparql and run to view

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?dzlabel ?lalabel ?rank 
WHERE 

{  
	?s <http://purl.org/linked-data/cube#dataSet>  <http://statistics.gov.scot/data/scottish-index-of-multiple-deprivation-2016> ;
  	<http://purl.org/linked-data/cube#measureType> <http://statistics.gov.scot/def/measure-properties/rank> ;
    <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> <http://reference.data.gov.uk/id/year/2016> ;
    <http://statistics.gov.scot/def/dimension/simdDomain> <http://statistics.gov.scot/def/concept/simd-domain/simd> ;
    <http://statistics.gov.scot/def/measure-properties/rank> ?rank ;
  	<http://purl.org/linked-data/sdmx/2009/dimension#refArea> ?dz .
?dz rdfs:label ?dzlabel .
?dz <http://statistics.gov.scot/def/hierarchy/best-fit#council-area> ?la .
?la rdfs:label ?lalabel .
}

